### ISSUE TITLE
docs: command line help for 'watch' and 'change'

### ISSUE THREAD

**Issue by xrouge** [zeux/qgrep#6]
Looks like there are 2 additional commands which are missing from printHelp: watch, change.

**Comment by zeux** [comment]
Yeah, they were somewhat experimental when they got added; they seem to be working fine now, although I have a few corner cases listed in my todo to fix.

Briefly, qgrep has a new functionality which is that it can track a set of loose files in addition to the pack database, and search through them in addition to the pack. The search is somewhat slower because these are loose files, so you'd usually keep the # of files there small.

qgrep watch works like qgrep update, but it keeps running and monitors changes in the folders; it automatically updates the change list and also updates the pack once the change list grows to be too big, to maintain good performance.

qgrep change is meant to be a standalone command that you run in your editor when saving the file if you don't want to use qgrep watch.

These only work on Windows right now, but I'll see about addition documentation for them.

**Comment by zeux** [comment]
FWIW I added documentation and also Linux & OSX support for watch mode.
